apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wdyw-ingress-{{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: wdyw-svc-{{ .Release.Name }}
              servicePort: 3000
          - path: /api/v1
            pathType: Prefix
            backend:
              serviceName: wdyw-svc-{{ .Release.Name }}
              servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-{{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: intress-nginx-{{ .Release.Name }}
    app.kubernetes.io/part-of: intress-nginx-{{ .Release.Name }}
  ports:
    - targetPort: http
      port: 80
      name: http
    - targetPort: https
      port: 443
      name: https
  type: LoadBalancer
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: nginx-ingress-controller
#  labels:
#    app: nginx-ingress-controller
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: nginx-ingress-controller
#  template:
#    metadata:
#      labels:
#        app: nginx-ingress-controller
#---
