apiVersion: v1
kind: Service
metadata:
  name: wdyw-svc-{{ .Release.Name }}
spec:
  selector:
    app: wdyw-app-{{ .Release.Name }}
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: server
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wdyw-app-{{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: wdyw-app-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: wdyw-app-{{ .Release.Name }}
    spec:
      containers:
        - name: client
          image: kanghun8871/wdyw:client
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
        - name: server
          image: kanghun8871/wdyw:server
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: mysql-svc-{{ .Release.Name }}
            - name: DB_NAME
              value: {{ .Values.mysql.db }}
            - name: DB_USER
              value: {{ .Values.mysql.user }}
            - name: DB_PASSWORD
              value: {{ .Values.mysql.password }}
      imagePullSecrets:
        - name: regcred